name: Update Taktile Code Nodes

on:
  push:
    branches:
      - main

jobs:
  update_taktile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r "${GITHUB_WORKSPACE}"/.github/workflows/taktile_github_integration/requirements.txt

      - name: Update Taktile Code Nodes
        env:
          Taktile_API_KEY: ${{ secrets.TAKTILE_API_KEY }}
          ORGANIZATION_NAME: "NB36"
        run: |
          python3 "${GITHUB_WORKSPACE}"/.github/workflows/taktile_github_integration/taktile_update_handler.py Taktile_API_KEY
